### ISSUE TITLE
How to compile/install etherwall in ubuntu?

### ISSUE THREAD

**Issue by mochechan** [almindor/etherwall#15]
The etherwall cannot be compiled in my ubuntu 16.04.1. 
$ sudo apt-get install qt5-default qtdeclarative5-dev
$ git clone https://github.com/almindor/etherwall.git
$ cd etherwall
$ qmake -config release 
$ make
src/transactionmodel.cpp:77:15: error: 'TransactionRoles' is not a class or namespace
  roles[TransactionRoles::THashRole] = "hash";
The make says "Makefile:631: recipe for target 'transactionmodel.o' failed
make: *** [transactionmodel.o] Error 1
How can I solve this problem? thanks.

**Comment by 5chdn** [comment]
Try to add `#include "types.h"` to `src/transactionmodel.cpp`. Just an idea.

**Comment by almindor** [comment]
Hmm that's an odd error. I'll try it in virtualbox. Which ubuntu version are you using?

**Comment by mochechan** [comment]
I am using ubuntu 16.04.1 LTS Thanks.

**Comment by mochechan** [comment]
To add #include "types.h" to src/transactionmodel.cpp does not work. Thanks.

**Comment by mochechan** [comment]
To add #include "types.h" to src/transactionmodel.cpp does not work. Thanks.

**Comment by almindor** [comment]
I've updated the branch `v1` with the fixes. Please use `v1` to build Etherwall for now as I'm currently in between v1 and v2 and v2 is too unstable atm.

I also had to install a couple of packages: `qt5-default build-essential qtdeclarative5-dev qml-module-qtquick-dialogs qml-module-qtquick-extras`

Another issue with ubuntu is that QT is outdated and does not have the QFileDialog.shortcuts object yet. This doesn't seem to cause a major problem but you will see errors like `ReferenceError: shortcuts is not defined`

Please re-open this issue if the build problems persist or you have other build issues.

**Comment by mochechan** [comment]
Thank you. 
After installing the packages you mentioned, and installing [https://wiki.qt.io/Install_Qt_5_on_Ubuntu](https://wiki.qt.io/Install_Qt_5_on_Ubuntu), the Etherwall can be built.
However, the Etherwall still cannot be executed. I opened another issue.
